// Generated by scripts/demo-assets/render.ts — do not edit by hand.
import type { Footprint } from "../types/project";

/** Footprint anchors of the placeholder pergola in public/demo/pergola/*.jpg (normalized image coords). */
export const DEMO_PERGOLA_FOOTPRINT: Footprint = {
  "FL": {
    "x": 0.1341,
    "y": 0.73683
  },
  "FR": {
    "x": 0.77279,
    "y": 0.75464
  },
  "BL": {
    "x": 0.29023,
    "y": 0.61662
  },
  "BR": {
    "x": 0.69339,
    "y": 0.62366
  }
};

/** Vertical field of view the placeholder scene was rendered with. */
export const DEMO_PERGOLA_FOV_DEG = 42;

export const DEMO_SPACE_SIZE = { width: 1920, height: 1280 };
