/**
 * Renders the PLACEHOLDER demo assets to public/demo and writes the generated demo footprint.
 * These are synthetic drawings, not photographs. No pre-rendered REALITY is produced: REALIDAD is
 * always composed over the original photograph at runtime (see src/lib/reality-composite.ts).
 *
 *   npx tsx scripts/demo-assets/render.ts
 */
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { sceneSvg, footprintForDemo, CAMERA, IMG_W, IMG_H } from "./scene";
import * as refs from "./refs";

const require = createRequire(import.meta.url);
const root = resolve(import.meta.dirname, "../..");
const out = resolve(root, "public/demo");
mkdirSync(resolve(out, "pergola"), { recursive: true });
mkdirSync(resolve(out, "kitchen"), { recursive: true });
mkdirSync(resolve(out, "facade"), { recursive: true });
mkdirSync(resolve(out, "lounge"), { recursive: true });
mkdirSync(resolve(out, "generic"), { recursive: true });

type Job = { file: string; svg: string; width: number; height: number };

const jobs: Job[] = [
  { file: "pergola/space.jpg", svg: sceneSvg("space"), width: IMG_W, height: IMG_H },
  { file: "pergola/archviz.jpg", svg: sceneSvg("archviz"), width: IMG_W, height: IMG_H },
  { file: "pergola/ref-front.jpg", svg: refs.pergolaFront(), width: 1600, height: 1200 },
  { file: "pergola/ref-side.jpg", svg: refs.pergolaSide(), width: 1600, height: 1200 },
  { file: "pergola/ref-detail.jpg", svg: refs.pergolaDetail(), width: 1600, height: 1200 },
  { file: "pergola/ref-material.jpg", svg: refs.pergolaMaterial(), width: 1600, height: 1200 },
  { file: "kitchen/ref-front.jpg", svg: refs.kitchenFront(), width: 1600, height: 1200 },
  { file: "kitchen/ref-material.jpg", svg: refs.kitchenMaterial(), width: 1600, height: 1200 },
  { file: "facade/ref-front.jpg", svg: refs.facadePanels(), width: 1600, height: 1200 },
  { file: "facade/ref-detail.jpg", svg: refs.facadeDetail(), width: 1600, height: 1200 },
  { file: "lounge/ref-front.jpg", svg: refs.loungeFront(), width: 1600, height: 1200 },
  { file: "lounge/ref-material.jpg", svg: refs.loungeMaterial(), width: 1600, height: 1200 },
  { file: "generic/archviz.jpg", svg: refs.genericOutput("ARCHVIZ"), width: 1920, height: 1280 },
];

async function main() {
  const playwrightPath = process.env.PLAYWRIGHT_MODULE ?? "/opt/node22/lib/node_modules/playwright";
  interface MinimalPage {
    setViewportSize(size: { width: number; height: number }): Promise<void>;
    setContent(html: string): Promise<void>;
    screenshot(opts: { type: "jpeg"; quality: number; clip: { x: number; y: number; width: number; height: number } }): Promise<Buffer>;
  }
  interface MinimalBrowser {
    newPage(): Promise<MinimalPage>;
    close(): Promise<void>;
  }
  const { chromium } = require(playwrightPath) as { chromium: { launch(o: { executablePath: string }): Promise<MinimalBrowser> } };
  const browser = await chromium.launch({
    executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
  });
  const page = await browser.newPage();
  for (const job of jobs) {
    await page.setViewportSize({ width: job.width, height: job.height });
    await page.setContent(`<!doctype html><html><body style="margin:0;background:#000">${job.svg}</body></html>`);
    const buf = await page.screenshot({ type: "jpeg", quality: 90, clip: { x: 0, y: 0, width: job.width, height: job.height } });
    writeFileSync(resolve(out, job.file), buf);
    console.log("wrote", job.file, `${(buf.length / 1024).toFixed(0)} KB`);
  }
  await browser.close();

  const fp = footprintForDemo();
  const generated = `// Generated by scripts/demo-assets/render.ts — do not edit by hand.
import type { Footprint } from "../types/project";

/** Footprint anchors of the placeholder pergola in public/demo/pergola/*.jpg (normalized image coords). */
export const DEMO_PERGOLA_FOOTPRINT: Footprint = ${JSON.stringify(fp, null, 2)};

/** Vertical field of view the placeholder scene was rendered with. */
export const DEMO_PERGOLA_FOV_DEG = ${CAMERA.fovDeg};

export const DEMO_SPACE_SIZE = { width: ${IMG_W}, height: ${IMG_H} };
`;
  writeFileSync(resolve(root, "src/core/demo/pergola-placement.generated.ts"), generated);
  console.log("wrote src/core/demo/pergola-placement.generated.ts", JSON.stringify(fp));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
